level_map = [
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'XP                           X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X                            X',
    'X     X                      X',
    'X     XXXXXXXXXXXXX          X',
    'X     X  X  X  X  XXXXXXX    X',
    'X                            X',
    'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
]